[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
startCommand = "gunicorn app:app"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2

[setup]
nixPkgs = ["...", "zbar"]
